name: .NET Core CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:    - name: Cargar el código fuente
      uses: actions/checkout@v4

    - name: Configurar el SDK de .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restaurar dependencias (Nuget) 
      run: dotnet restore ./ProcessingSystem/ProcessingSystem.sln
 
    - name: Compilar la solución
      run: dotnet build ./ProcessingSystem/ProcessingSystem.sln --no-restore --configuration Release

    - name: Ejecutar Pruebas Unitarias
      run: dotnet test ./ProcessingSystem/ProcessingSystem.sln --no-build --configuration Release --verbosity normal
